site_name: node-event-storage
repo_url: https://github.com/albe/node-event-storage

theme: readthedocs

markdown_extensions:
  - admonition
  - tables

plugins:
  - search
  - mermaid2

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Event Streams: streams.md
  - Consumers: consumers.md
  - Advanced Topics: advanced.md
  - Implementation Architecture: architecture.md
  - Upgrading from 0.x to 1.0: upgrading.md
