site_name: node-event-storage
repo_url: https://github.com/albe/node-event-storage

theme: readthedocs

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: True
  - mdx_sections
